/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iceicelee.nppa;

import com.iceicelee.nppa.utils.TestUrlProvider;
import org.apache.commons.lang3.StringUtils;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * 中宣部的网络游戏防沉迷实名认证系统 接口测试</p>
 * 想提供一个工具 把其中的测试都通过，省的来来回回的测接口
 *
 * @author Yao Shuai
 * @date: 2021/3/26 19:12
 */
public class NppaPassTester {

    private TestUrlProvider urlProvider;

    public NppaPassTester() {
        this.urlProvider = new TestUrlProvider();
    }

    public static void main(String[] args) {
        NppaPassTester tester = new NppaPassTester();
        tester.begin();
    }

    private void begin() {
        System.out.println("选1-8");
        int testNum = 0;
        String testCode = null;
        try {
            testNum = System.in.read();
            if (testNum > 0 && testNum < 9) {
                BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
                testCode = reader.readLine();
                if (StringUtils.isEmpty(testCode)) {
                    throw new IllegalArgumentException("测试码格式不正确!");
                }
            }
        } catch (IOException e) {
            System.out.println("输入1-8测试用例：");
            e.printStackTrace();
        }
        switch (testNum) {
            case 1 :
                testcase01(testCode);
                break;
            case 2 :

                break;
            case 3 :

                break;
            case 4 :

                break;
            case 5 :

                break;
            case 6 :

                break;
            case 7 :

                break;
            case 8 :

                break;
        }
    }

    private void testcase01(String testCode) {
        String urlStr = this.urlProvider.getTestUrl(1, testCode);

    }


}
