/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iceicelee;

import com.iceicelee.nppa.NppaPassTester;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        NppaPassTester classUnderTest = new NppaPassTester();
    }
}
